using System.Collections.Generic;
namespace CdrDecoder
{
    internal class Nokia
    {

        public enum CdrType
        {
           Ptc,
           Poc
        }

        public enum DataType
        {
            TimeFieldDate,
            HexByte,
            HexByteRev,
            HexWord,
            HexDword,
            BcdByte,
            BcdByteRev,

            BcdWord,
            BcdDword,
            WordWordByte,
            BcdBcdHex,
            BcdBcdWord,
            HexWordHexbyte,
            Unknown
        }
        public static List<string> FieldList = new List<string>()
        {
            "record_length",
            "record_type",
            "record_number",
            "record_status",
            "check_sum",
            "call_reference",
            "exchange_id",
            "intermediate_record_number",
            "intermediate_charging_ind",
            "number_of_ss_records",
            "calling_number_ton",
            "calling_number",
            "called_number_ton",
            "called_number",
            "out_circuit_group",
            "out_circuit",
            "in_channel_allocated_time",
            "charging_start_time",
            "charging_end_time",
            "cause_for_termination",
            "call_type",
            "ticket_type",
            "oaz_chrg_type",
            "oaz_duration",
            "oaz_tariff_class",
            "oaz_pulses",
            "called_msrn_ton",
            "called_msrn",
            "intermediate_chrg_cause",
            // "leg_call_reference",
            // "out_channel_allocated_time",
            "basic_service_type",
            "basic_service_code",
            // "call_reference_time",
            "number_of_all_in_records",
            "char_band_change_direction",
            "char_band_change_percent",
            "number_of_in_records",
            "oaz_change_direction",
            "oaz_change_percent",
            "scp_connection",
            "term_mcz_change_direction",
            "term_mcz_change_percent",
            "cug_information",
            "cug_interlock",
            "cug_outgoing_access",
            "selected_codec",
            "out_bnc_connection_type",
            "outside_control_plane_index",
            "outside_user_plane_index",
            "in_circuit_group_name",
            "out_circuit_group_name",
            "in_circuit",
            "in_circuit_group",
            "oaz_duration_ten_ms"
        };

        public static Dictionary<string, Nokiaseimens.FieldInfo> PocFieldsDetails =
          new Dictionary<string, Nokiaseimens.FieldInfo>()
          {
               { "record_length", new Nokiaseimens.FieldInfo(0, 2,Nokia.DataType.HexWord )},
               { "record_type", new Nokiaseimens.FieldInfo(2, 1,Nokia.DataType.HexByteRev) },
               { "record_number", new Nokiaseimens.FieldInfo(3, 4,Nokia.DataType.HexByteRev)},
               { "record_status", new Nokiaseimens.FieldInfo(7, 1, Nokia.DataType.HexByte) },
               { "check_sum", new Nokiaseimens.FieldInfo(8, 2, Nokia.DataType.HexWord) },
               { "call_reference", new Nokiaseimens.FieldInfo(10, 5,Nokia.DataType.WordWordByte ) },
               { "exchange_id", new Nokiaseimens.FieldInfo(15, 10,Nokia.DataType.BcdByte) },
               { "intermediate_record_number", new Nokiaseimens.FieldInfo(25, 1,Nokia.DataType.BcdByte) },
               { "intermediate_charging_ind", new Nokiaseimens.FieldInfo(26, 1, Nokia.DataType.HexByte) },
               { "number_of_ss_records", new Nokiaseimens.FieldInfo(27, 1, Nokia.DataType.BcdByte) },
               { "calling_number_ton", new Nokiaseimens.FieldInfo(28, 1, Nokia.DataType.HexByte) },
               { "calling_number", new Nokiaseimens.FieldInfo(29, 12, Nokia.DataType.BcdByte) },
               { "called_number_ton", new Nokiaseimens.FieldInfo(41, 1, Nokia.DataType.HexByte) },
               { "called_number", new Nokiaseimens.FieldInfo(42, 12, Nokia.DataType.BcdByte) },
               { "out_circuit_group", new Nokiaseimens.FieldInfo(52, 2, Nokia.DataType.BcdWord) },
               { "out_circuit", new Nokiaseimens.FieldInfo(54, 2, Nokia.DataType.BcdWord) },
               { "in_channel_allocated_time", new Nokiaseimens.FieldInfo(58, 7, Nokia.DataType.TimeFieldDate) },
               { "charging_start_time", new Nokiaseimens.FieldInfo(65, 7, Nokia.DataType.TimeFieldDate) },
               { "charging_end_time", new Nokiaseimens.FieldInfo(72, 7, Nokia.DataType.TimeFieldDate) },
               { "cause_for_termination", new Nokiaseimens.FieldInfo(79, 4, Nokia.DataType.HexDword) },
               { "call_type", new Nokiaseimens.FieldInfo(83, 1, Nokia.DataType.HexByte) },
               { "ticket_type", new Nokiaseimens.FieldInfo(84, 1,Nokia.DataType.HexByte) }, //Type of CDR POC/PTC 
               { "oaz_chrg_type", new Nokiaseimens.FieldInfo(85, 1,Nokia.DataType.HexByte) },
               { "oaz_duration", new Nokiaseimens.FieldInfo(86, 3,Nokia.DataType.BcdByteRev) },
               { "oaz_tariff_class", new Nokiaseimens.FieldInfo(89, 3,DataType.HexWordHexbyte) },
               { "oaz_pulses", new Nokiaseimens.FieldInfo(92, 2,DataType.BcdWord) },
               { "called_msrn_ton", new Nokiaseimens.FieldInfo(94, 1,DataType.HexByte) },
               { "called_msrn", new Nokiaseimens.FieldInfo(95, 12, DataType.HexByte) },
               { "intermediate_chrg_cause", new Nokiaseimens.FieldInfo(107, 4, DataType.HexDword) },
               { "leg_call_reference", new Nokiaseimens.FieldInfo(111, 1,DataType.HexByte) },
               { "out_channel_allocated_time", new Nokiaseimens.FieldInfo(112, 5,DataType.HexByte) },//Change Type
               { "basic_service_type", new Nokiaseimens.FieldInfo(118, 1,DataType.HexByte) },
               { "basic_service_code", new Nokiaseimens.FieldInfo(119, 1,DataType.HexByte) },
               { "call_reference_time", new Nokiaseimens.FieldInfo(120, 7,DataType.TimeFieldDate) },
               { "number_of_all_in_records", new Nokiaseimens.FieldInfo(127, 8,DataType.HexByte) },
               { "char_band_change_direction", new Nokiaseimens.FieldInfo(135, 9, DataType.HexByte) },
               { "char_band_change_percent", new Nokiaseimens.FieldInfo(144, 1, DataType.HexByte) },
               { "number_of_in_records", new Nokiaseimens.FieldInfo(145, 1,DataType.BcdByte) },
               { "oaz_change_direction", new Nokiaseimens.FieldInfo(146, 1,DataType.HexByte) },
               { "oaz_change_percent", new Nokiaseimens.FieldInfo(147, 1,DataType.HexByte) },
               { "scp_connection", new Nokiaseimens.FieldInfo(148, 1, DataType.HexByte) },
               { "term_mcz_change_direction", new Nokiaseimens.FieldInfo(149, 1,DataType.HexByte) },
               { "term_mcz_change_percent", new Nokiaseimens.FieldInfo(150, 1, DataType.HexByte) },
               { "cug_information", new Nokiaseimens.FieldInfo(151, 1, DataType.HexByte) },
               { "cug_interlock", new Nokiaseimens.FieldInfo(152, 1,DataType.HexByte) },
               { "cug_outgoing_access", new Nokiaseimens.FieldInfo(153, 1, DataType.HexByte) },
               { "selected_codec", new Nokiaseimens.FieldInfo(154, 1, DataType.HexByte) },
               { "out_bnc_connection_type", new Nokiaseimens.FieldInfo(155, 4, DataType.HexByte) },
               { "outside_control_plane_index", new Nokiaseimens.FieldInfo(159, 1,DataType.HexByte) },
               { "outside_user_plane_index", new Nokiaseimens.FieldInfo(160, 1,DataType.HexByte) },
               { "in_circuit_group_name", new Nokiaseimens.FieldInfo(161, 1,DataType.HexByte) },
               { "out_circuit_group_name", new Nokiaseimens.FieldInfo(162, 2,DataType.HexByte) },
               { "in_circuit", new Nokiaseimens.FieldInfo(164, 2,DataType.HexByte) },
               { "in_circuit_group", new Nokiaseimens.FieldInfo(166, 6,DataType.HexByte) },
               { "oaz_duration_ten_ms", new Nokiaseimens.FieldInfo(172, 8,DataType.HexByte) }

          };
        public static Dictionary<string, Nokiaseimens.FieldInfo> PtcFieldsDetails =
  new Dictionary<string, Nokiaseimens.FieldInfo>()
  {
               { "record_length", new Nokiaseimens.FieldInfo(0, 2,DataType.HexWord )},
               { "record_type", new Nokiaseimens.FieldInfo(2, 1,DataType.HexByteRev) },
               { "record_number", new Nokiaseimens.FieldInfo(3, 4,DataType.HexByteRev)},
               { "record_status", new Nokiaseimens.FieldInfo(7, 1, DataType.HexByte) },
               { "check_sum", new Nokiaseimens.FieldInfo(8, 2, DataType.HexWord) },
               { "call_reference", new Nokiaseimens.FieldInfo(10, 5,DataType.WordWordByte ) },
               { "exchange_id", new Nokiaseimens.FieldInfo(15, 10,DataType.BcdByte) },
               { "intermediate_record_number", new Nokiaseimens.FieldInfo(25, 1,DataType.BcdByte) },
               { "intermediate_charging_ind", new Nokiaseimens.FieldInfo(26, 1, DataType.HexByte) },
               { "number_of_ss_records", new Nokiaseimens.FieldInfo(27, 1, Nokia.DataType.BcdByte) },
               { "calling_number_ton", new Nokiaseimens.FieldInfo(28, 1, DataType.HexByte) },
               { "calling_number", new Nokiaseimens.FieldInfo(29, 12, DataType.BcdByte) },
               { "called_number_ton", new Nokiaseimens.FieldInfo(41, 1, DataType.HexByte) },
               { "called_number", new Nokiaseimens.FieldInfo(42, 12, DataType.BcdByte) },
               { "out_circuit_group", new Nokiaseimens.FieldInfo(54, 2, DataType.BcdWord) },
               { "out_circuit", new Nokiaseimens.FieldInfo(56, 2, DataType.BcdWord) },
               { "in_channel_allocated_time", new Nokiaseimens.FieldInfo(58, 7, DataType.TimeFieldDate) },
               { "charging_start_time", new Nokiaseimens.FieldInfo(65, 7, DataType.TimeFieldDate) },
               { "charging_end_time", new Nokiaseimens.FieldInfo(72, 7, DataType.TimeFieldDate) },
               { "cause_for_termination", new Nokiaseimens.FieldInfo(79, 4, DataType.HexDword) },
               { "call_type", new Nokiaseimens.FieldInfo(83, 1, DataType.HexByte) },
               { "ticket_type", new Nokiaseimens.FieldInfo(84, 1,DataType.HexByte) }, //Type of CDR POC/PTC 
               { "oaz_chrg_type", new Nokiaseimens.FieldInfo(85, 1,DataType.HexByte) },
               { "oaz_duration", new Nokiaseimens.FieldInfo(86, 3,DataType.BcdByteRev) },
               { "oaz_tariff_class", new Nokiaseimens.FieldInfo(89, 3,DataType.HexWordHexbyte) },
               { "oaz_pulses", new Nokiaseimens.FieldInfo(92, 2,DataType.BcdWord) },
               { "called_msrn_ton", new Nokiaseimens.FieldInfo(94, 1,DataType.HexByte) },
               { "called_msrn", new Nokiaseimens.FieldInfo(95, 12, DataType.HexByte) },
               { "intermediate_chrg_cause", new Nokiaseimens.FieldInfo(107, 4, DataType.HexDword) },
               { "leg_call_reference", new Nokiaseimens.FieldInfo(111, 5,DataType.WordWordByte) }, //poc
               { "out_channel_allocated_time", new Nokiaseimens.FieldInfo(116, 7,DataType.TimeFieldDate) },//Change Type
               { "basic_service_type", new Nokiaseimens.FieldInfo(123, 1,DataType.HexByte) },
               { "basic_service_code", new Nokiaseimens.FieldInfo(124, 1,DataType.HexByte) },
               { "call_reference_time", new Nokiaseimens.FieldInfo(125, 7,DataType.TimeFieldDate) },
               { "number_of_all_in_records", new Nokiaseimens.FieldInfo(132, 1,DataType.HexByte) },
               { "char_band_change_direction", new Nokiaseimens.FieldInfo(133, 1, DataType.HexByte) },
               { "char_band_change_percent", new Nokiaseimens.FieldInfo(134, 1, DataType.HexByte) },
               { "number_of_in_records", new Nokiaseimens.FieldInfo(135, 1,DataType.BcdByte) },
               { "oaz_change_direction", new Nokiaseimens.FieldInfo(136, 1,DataType.HexByte) },
               { "oaz_change_percent", new Nokiaseimens.FieldInfo(137, 1,DataType.HexByte) },
               { "scp_connection", new Nokiaseimens.FieldInfo(138, 1, DataType.HexByte) },
               { "term_mcz_change_direction", new Nokiaseimens.FieldInfo(139, 1,DataType.HexByte) },
               { "term_mcz_change_percent", new Nokiaseimens.FieldInfo(140, 1, DataType.HexByte) },
               { "cug_information", new Nokiaseimens.FieldInfo(141, 1, DataType.HexByte) },
              { "cug_interlock", new Nokiaseimens.FieldInfo(142, 4,DataType.HexByte) },
              { "cug_outgoing_access", new Nokiaseimens.FieldInfo(146, 1, DataType.HexByte) },
              { "selected_codec", new Nokiaseimens.FieldInfo(147, 1, DataType.HexByte) },
              { "out_bnc_connection_type", new Nokiaseimens.FieldInfo(148, 1, DataType.HexByte) },
              { "outside_control_plane_index", new Nokiaseimens.FieldInfo(149, 2,DataType.HexByte) },
              { "outside_user_plane_index", new Nokiaseimens.FieldInfo(151, 2,DataType.HexByte) },
              { "in_circuit_group_name", new Nokiaseimens.FieldInfo(153, 8,DataType.HexByte) },
              { "out_circuit_group_name", new Nokiaseimens.FieldInfo(161, 8,DataType.HexByte) },
              { "in_circuit", new Nokiaseimens.FieldInfo(169, 2,DataType.BcdWord) },
              { "in_circuit_group", new Nokiaseimens.FieldInfo(171, 2,DataType.BcdWord) },
              { "oaz_duration_ten_ms", new Nokiaseimens.FieldInfo(173, 4,DataType.BcdByteRev) }

  };
    }
}
